//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kochi_TVM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CancelTicket
    {
        public long recId { get; set; }
        public string ticketId { get; set; }
        public Nullable<byte> tranType { get; set; }
        public Nullable<decimal> cancelAmount { get; set; }
        public string paymentType { get; set; }
        public Nullable<int> stationId { get; set; }
        public Nullable<int> salePointId { get; set; }
        public Nullable<int> insertUserId { get; set; }
        public Nullable<System.DateTime> insertDT { get; set; }
        public Nullable<System.DateTime> syncDT { get; set; }
    }
}
