//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kochi_TVM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Command
    {
        public decimal Id { get; set; }
        public decimal Status { get; set; }
        public System.DateTime OperationDts { get; set; }
        public string Type { get; set; }
        public string Source { get; set; }
        public string Command1 { get; set; }
        public string CommandData { get; set; }
        public string CommandResult { get; set; }
        public string IsDone { get; set; }
        public Nullable<System.DateTime> DoneDts { get; set; }
        public string Description { get; set; }
    }
}
