//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kochi_TVM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Language
    {
        public decimal Id { get; set; }
        public decimal Status { get; set; }
        public System.DateTime OperationDts { get; set; }
        public string LanguageCode { get; set; }
        public string LanguageName { get; set; }
        public decimal IsActive { get; set; }
        public string DateFormat { get; set; }
        public string TimeFormat { get; set; }
        public string CurrencyCode { get; set; }
        public string CultureInfoCode { get; set; }
        public string Description { get; set; }
    }
}
