//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kochi_TVM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public int recId { get; set; }
        public string channelCd { get; set; }
        public string descCode { get; set; }
        public string url { get; set; }
        public Nullable<int> topMenuId { get; set; }
        public Nullable<int> menuOrder { get; set; }
        public string iconCssClass { get; set; }
        public Nullable<int> inserUserId { get; set; }
        public Nullable<System.DateTime> insertDT { get; set; }
        public Nullable<int> editUserId { get; set; }
        public Nullable<System.DateTime> editDT { get; set; }
        public byte isActive { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public Nullable<int> type { get; set; }
    }
}
