//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kochi_TVM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MoneyDetail
    {
        public decimal Id { get; set; }
        public decimal Status { get; set; }
        public System.DateTime OperationDts { get; set; }
        public Nullable<decimal> TrxGuid { get; set; }
        public string IO { get; set; }
        public Nullable<decimal> Order { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> IndexNo { get; set; }
        public string Device { get; set; }
        public string HoldBox { get; set; }
    }
}
