//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kochi_TVM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PenaltyTicket
    {
        public long recId { get; set; }
        public Nullable<long> transactionId { get; set; }
        public string mediaType { get; set; }
        public Nullable<short> reasonId { get; set; }
        public Nullable<decimal> penaltyFee { get; set; }
        public Nullable<int> stationId { get; set; }
        public Nullable<int> salePointId { get; set; }
        public Nullable<int> insertUserId { get; set; }
        public System.DateTime insertDT { get; set; }
        public Nullable<int> editUserId { get; set; }
        public System.DateTime editDate { get; set; }
        public bool isDeleted { get; set; }
        public Nullable<System.DateTime> syncDT { get; set; }
        public string authCode { get; set; }
        public Nullable<System.DateTime> settlementDate { get; set; }
        public Nullable<System.DateTime> reconciliationDate { get; set; }
    }
}
