//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kochi_TVM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QRCodeTicket
    {
        public long recId { get; set; }
        public string QRCodeId { get; set; }
        public Nullable<int> QRCodeType { get; set; }
        public string QRCreateMode { get; set; }
        public Nullable<int> QRCreateStation { get; set; }
        public Nullable<int> QRCreateSalePointId { get; set; }
        public Nullable<int> transactionId { get; set; }
        public Nullable<decimal> QRCodePrice { get; set; }
        public Nullable<int> fromSectionId { get; set; }
        public Nullable<int> toSectionId { get; set; }
        public Nullable<int> ticketStatusId { get; set; }
        public Nullable<System.DateTime> insertDT { get; set; }
        public Nullable<System.DateTime> editDT { get; set; }
        public Nullable<System.DateTime> activeFrom { get; set; }
        public Nullable<System.DateTime> activeTo { get; set; }
        public Nullable<short> peopleCount { get; set; }
        public Nullable<int> alias { get; set; }
        public bool isDeleted { get; set; }
        public Nullable<int> printSalePointId { get; set; }
        public Nullable<System.DateTime> printDT { get; set; }
        public string QRCodeUId { get; set; }
        public Nullable<int> QRCreateUserId { get; set; }
        public Nullable<System.DateTime> syncDT { get; set; }
        public string authCode { get; set; }
        public Nullable<System.DateTime> settlementDate { get; set; }
        public Nullable<System.DateTime> reconciliationDate { get; set; }
    }
}
