//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kochi_TVM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalePointDevice
    {
        public int recId { get; set; }
        public short salePointId { get; set; }
        public long deviceId { get; set; }
        public Nullable<int> insertUserId { get; set; }
        public System.DateTime insertDT { get; set; }
        public Nullable<int> editUserId { get; set; }
        public System.DateTime editDT { get; set; }
        public bool isDeleted { get; set; }
    }
}
