//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kochi_TVM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stations1
    {
        public int recId { get; set; }
        public int stationTypeId { get; set; }
        public string stationCode { get; set; }
        public string latitude { get; set; }
        public string longitude { get; set; }
        public string altitude { get; set; }
        public Nullable<int> panelId { get; set; }
        public Nullable<int> insertUserId { get; set; }
        public System.DateTime insertDT { get; set; }
        public Nullable<int> editUserId { get; set; }
        public System.DateTime editDT { get; set; }
        public string latitudeF { get; set; }
        public string longitudeF { get; set; }
        public byte isActive { get; set; }
        public bool isDeleted { get; set; }
        public string descCode { get; set; }
        public Nullable<int> sequenceNumber { get; set; }
        public string ipAddress { get; set; }
        public Nullable<int> mapRow { get; set; }
        public Nullable<int> mapColumn { get; set; }
        public Nullable<int> mapHereRow { get; set; }
        public Nullable<int> mapHereColumn { get; set; }
        public Nullable<decimal> totalDistance { get; set; }
        public Nullable<int> downTownSeq { get; set; }
        public Nullable<int> stationNo { get; set; }
        public int institutionId { get; set; }
    }
}
