//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kochi_TVM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockDetail
    {
        public long recId { get; set; }
        public long trxId { get; set; }
        public int updType { get; set; }
        public int stockType { get; set; }
        public int deviceType { get; set; }
        public int firstQty { get; set; }
        public int quantity { get; set; }
        public int lastQty { get; set; }
    }
}
