//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kochi_TVM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketSubType
    {
        public int recId { get; set; }
        public int ticketTypeId { get; set; }
        public int tripCount { get; set; }
        public Nullable<int> insertUserId { get; set; }
        public System.DateTime insertDT { get; set; }
        public Nullable<int> editUserId { get; set; }
        public System.DateTime editDT { get; set; }
        public Nullable<byte> isActive { get; set; }
        public bool isDeleted { get; set; }
        public Nullable<int> descId { get; set; }
        public Nullable<int> addTripCount { get; set; }
        public Nullable<int> validMonthCount { get; set; }
        public Nullable<int> renewalLimit { get; set; }
        public Nullable<bool> refundable { get; set; }
        public Nullable<decimal> multiplier { get; set; }
        public Nullable<int> validDayCount { get; set; }
        public Nullable<System.DateTime> validityStartDT { get; set; }
        public Nullable<System.DateTime> validityEndDT { get; set; }
        public Nullable<decimal> passAmount { get; set; }
        public string hindi { get; set; }
        public string loyaltyType { get; set; }
        public Nullable<int> freeRideCount { get; set; }
        public Nullable<int> topupTrashold { get; set; }
        public Nullable<int> bonusPercentage { get; set; }
        public Nullable<int> tripTrashold { get; set; }
        public int institutionId { get; set; }
        public Nullable<bool> isValidForAll { get; set; }
    }
}
