//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kochi_TVM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketTransactionDetail
    {
        public long recId { get; set; }
        public Nullable<long> sessionNo { get; set; }
        public Nullable<byte> isActive { get; set; }
        public Nullable<decimal> totalAmount { get; set; }
        public Nullable<byte> tranType { get; set; }
        public Nullable<byte> paymentType { get; set; }
        public Nullable<decimal> cashAmount { get; set; }
        public Nullable<decimal> creditCardAmount { get; set; }
        public Nullable<decimal> cashPayment { get; set; }
        public Nullable<decimal> creditCardPayment { get; set; }
        public Nullable<decimal> change { get; set; }
        public Nullable<int> insUserId { get; set; }
        public Nullable<System.DateTime> insDT { get; set; }
        public Nullable<int> editUserId { get; set; }
        public Nullable<System.DateTime> editDT { get; set; }
        public Nullable<short> isDeleted { get; set; }
        public Nullable<int> salePointId { get; set; }
        public Nullable<long> OCCTransactionId { get; set; }
        public Nullable<int> stationId { get; set; }
        public Nullable<System.DateTime> syncDT { get; set; }
        public Nullable<long> shiftId { get; set; }
        public Nullable<decimal> upiAmount { get; set; }
        public Nullable<decimal> upiPayment { get; set; }
        public Nullable<byte> peakTypeId { get; set; }
    }
}
