//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kochi_TVM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketDetail
    {
        public decimal Id { get; set; }
        public decimal Status { get; set; }
        public System.DateTime OperationDts { get; set; }
        public Nullable<decimal> TrxGuid { get; set; }
        public string GUID { get; set; }
        public string TicketType { get; set; }
        public string JourneyType { get; set; }
        public string StartStation { get; set; }
        public string EndStation { get; set; }
        public Nullable<System.DateTime> ActivateDts { get; set; }
        public Nullable<System.DateTime> ExpiryDts { get; set; }
        public Nullable<decimal> TicketCount { get; set; }
        public Nullable<decimal> PeopleCount { get; set; }
        public Nullable<decimal> TicketPrice { get; set; }
    }
}
