//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kochi_TVM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Topup
    {
        public long recId { get; set; }
        public Nullable<int> stationId { get; set; }
        public Nullable<int> salePointId { get; set; }
        public Nullable<long> transactionId { get; set; }
        public Nullable<System.DateTime> trxDT { get; set; }
        public string merchantCode { get; set; }
        public string rrn { get; set; }
        public string clessId { get; set; }
        public string pan { get; set; }
        public string currencyCode { get; set; }
        public string tranId { get; set; }
        public string terminalId { get; set; }
        public string stan { get; set; }
        public string batchNo { get; set; }
        public Nullable<decimal> topupAmount { get; set; }
        public Nullable<decimal> topupFee { get; set; }
        public Nullable<decimal> globalBalance { get; set; }
        public System.DateTime insertDT { get; set; }
        public System.DateTime editDT { get; set; }
        public bool isDeleted { get; set; }
        public Nullable<System.DateTime> syncDT { get; set; }
        public Nullable<int> insUserId { get; set; }
        public Nullable<int> topupTypeId { get; set; }
        public Nullable<int> topupTripCount { get; set; }
        public Nullable<int> passFromStationId { get; set; }
        public Nullable<int> passToStationId { get; set; }
        public Nullable<int> previousTripCount { get; set; }
        public Nullable<int> totalTripCount { get; set; }
        public Nullable<System.DateTime> validityStartDT { get; set; }
        public Nullable<System.DateTime> validityEndDT { get; set; }
        public Nullable<int> subTypeId { get; set; }
    }
}
