//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kochi_TVM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public decimal Id { get; set; }
        public decimal Status { get; set; }
        public System.DateTime OperationDts { get; set; }
        public Nullable<decimal> TrxGuid { get; set; }
        public string TrxType { get; set; }
        public string CardId { get; set; }
        public string TicketType { get; set; }
        public Nullable<decimal> Batch { get; set; }
        public Nullable<decimal> Stan { get; set; }
        public string RefNo { get; set; }
        public Nullable<decimal> TicketPrice { get; set; }
        public Nullable<decimal> PaidAmount { get; set; }
        public Nullable<decimal> ChangeAmount { get; set; }
        public string ErrCode { get; set; }
        public decimal EodStatus { get; set; }
        public System.DateTime EodDts { get; set; }
        public decimal SyncStatus { get; set; }
        public System.DateTime SyncDts { get; set; }
        public string PaymentType { get; set; }
    }
}
