//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kochi_TVM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transactions1
    {
        public long recId { get; set; }
        public long trxTypeId { get; set; }
        public System.DateTime trxDate { get; set; }
        public Nullable<System.DateTime> syncDT { get; set; }
    }
}
