//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kochi_TVM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionType1
    {
        public decimal Id { get; set; }
        public decimal Status { get; set; }
        public System.DateTime OperationDts { get; set; }
        public string Type { get; set; }
        public string TxnName { get; set; }
        public string IsFınancial { get; set; }
        public string IsAdmin { get; set; }
        public string MustSync { get; set; }
        public string GiveReceipt { get; set; }
        public string GiveChange { get; set; }
        public string GiveBanknote { get; set; }
        public string CollectCoin { get; set; }
        public string CollectBanknote { get; set; }
        public string Description { get; set; }
    }
}
