//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kochi_TVM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TVMAlarm
    {
        public int recId { get; set; }
        public Nullable<int> stationId { get; set; }
        public Nullable<int> deviceNo { get; set; }
        public Nullable<int> alarmTypeId { get; set; }
        public string alarmMessage { get; set; }
        public Nullable<bool> alarmStatus { get; set; }
        public Nullable<System.DateTime> insertDT { get; set; }
        public Nullable<System.DateTime> editDT { get; set; }
        public Nullable<System.DateTime> syncDT { get; set; }
    }
}
