//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kochi_TVM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TVMInfo
    {
        public decimal recId { get; set; }
        public System.DateTime operationDts { get; set; }
        public string infoKey { get; set; }
        public string infoValue { get; set; }
        public string description { get; set; }
        public Nullable<byte> isActive { get; set; }
        public Nullable<bool> isDeleted { get; set; }
    }
}
